# App
- hosts: app
  gather_facts: false
  vars:
    manala_ansible_galaxy_roles:
      - manala.ansible-galaxy
      - manala.skeleton
      - geerlingguy.mysql
      - aeriscloud.wkhtmltopdf
  roles:
    - manala.ansible-galaxy

# Global
- hosts: all
  gather_facts: false
  vars:
    manala_ansible_galaxy_roles_path: "{{ playbook_dir }}/roles"
    manala_ansible_galaxy_roles:
      - manala.ansible-galaxy
  roles:
    - manala.ansible-galaxy

# Ansible
- hosts: all
  gather_facts: true
  vars:
    # App
    app: "{{ manala_skeleton_options.app }}"
    # Manala
    manala_skeleton_name: manala_app_php
    manala_skeleton_env: "{{ env }}"
    manala_skeleton_options_hashes:
      - app_options
      - app_options_env
    manala_skeleton_patterns_hashes:
      - app_patterns
      - app_patterns_env
  roles:
    - manala.skeleton
