- hosts: all
  become: true
  roles:
    - aeriscloud.wkhtmltopdf
    - geerlingguy.mysql
    - mysql

- hosts: all
  become: yes
  roles:
      - { role: common }

- hosts: all
  become: yes
  become_user: app
  roles:
      - { role: app }

